/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas1;

import java.lang.reflect.Field;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormFeedback extends javax.swing.JFrame {

    /**
     * Creates new form FormFeedback
     */
    public FormFeedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSatisfication = new javax.swing.ButtonGroup();
        LabelFeedback = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        LabelSatisfication = new javax.swing.JLabel();
        RadioButton1 = new javax.swing.JRadioButton();
        RadioButton2 = new javax.swing.JRadioButton();
        RadioButton3 = new javax.swing.JRadioButton();
        RadioButton4 = new javax.swing.JRadioButton();
        RadioButton5 = new javax.swing.JRadioButton();
        LabelFeatures = new javax.swing.JLabel();
        CheckBoxDesign = new javax.swing.JCheckBox();
        CheckBoxPerformance = new javax.swing.JCheckBox();
        CheckBoxUsability = new javax.swing.JCheckBox();
        LabelHear = new javax.swing.JLabel();
        ComboBoxHear = new javax.swing.JComboBox<>();
        ButtonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(480, 360));
        setResizable(false);

        LabelFeedback.setFont(new java.awt.Font("Google Sans Medium", 1, 24)); // NOI18N
        LabelFeedback.setText("Feedback Form");

        LabelName.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        LabelName.setText("Name");

        TextFieldName.setColumns(10);
        TextFieldName.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        TextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNameActionPerformed(evt);
            }
        });

        LabelSatisfication.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        LabelSatisfication.setText("Satisfication Level");

        buttonGroupSatisfication.add(RadioButton1);
        RadioButton1.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        RadioButton1.setText("1");
        RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton1ActionPerformed(evt);
            }
        });

        buttonGroupSatisfication.add(RadioButton2);
        RadioButton2.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        RadioButton2.setText("2");
        RadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton2ActionPerformed(evt);
            }
        });

        buttonGroupSatisfication.add(RadioButton3);
        RadioButton3.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        RadioButton3.setText("3");
        RadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton3ActionPerformed(evt);
            }
        });

        buttonGroupSatisfication.add(RadioButton4);
        RadioButton4.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        RadioButton4.setText("4");
        RadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton4ActionPerformed(evt);
            }
        });

        buttonGroupSatisfication.add(RadioButton5);
        RadioButton5.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        RadioButton5.setText("5");
        RadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton5ActionPerformed(evt);
            }
        });

        LabelFeatures.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        LabelFeatures.setText("What you love about");

        CheckBoxDesign.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        CheckBoxDesign.setText("Design");
        CheckBoxDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxDesignActionPerformed(evt);
            }
        });

        CheckBoxPerformance.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        CheckBoxPerformance.setText("Performance");
        CheckBoxPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxPerformanceActionPerformed(evt);
            }
        });

        CheckBoxUsability.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        CheckBoxUsability.setText("Usability");
        CheckBoxUsability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxUsabilityActionPerformed(evt);
            }
        });

        LabelHear.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        LabelHear.setText("Where you hear us from");

        ComboBoxHear.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        ComboBoxHear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Social Media", "Friends/Colleague", "Communities" }));

        ButtonSend.setFont(new java.awt.Font("Google Sans", 0, 18)); // NOI18N
        ButtonSend.setText("Send");
        ButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(LabelFeedback)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(ButtonSend))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelFeatures)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButton3)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(RadioButton5))
                            .addComponent(LabelSatisfication)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CheckBoxDesign)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBoxPerformance))
                                    .addComponent(LabelHear))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(ComboBoxHear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CheckBoxUsability)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(LabelFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSatisfication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButton1)
                    .addComponent(RadioButton2)
                    .addComponent(RadioButton3)
                    .addComponent(RadioButton4)
                    .addComponent(RadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelFeatures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxDesign)
                    .addComponent(CheckBoxPerformance)
                    .addComponent(CheckBoxUsability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxHear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHear))
                .addGap(18, 18, 18)
                .addComponent(ButtonSend)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNameActionPerformed

    private void RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton1ActionPerformed

    private void RadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton2ActionPerformed

    private void RadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton3ActionPerformed

    private void RadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton4ActionPerformed

    private void RadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton5ActionPerformed

    private void CheckBoxDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxDesignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxDesignActionPerformed

    private void CheckBoxPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxPerformanceActionPerformed

    private void CheckBoxUsabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxUsabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxUsabilityActionPerformed

    private void ButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSendActionPerformed
        // TODO add your handling code here:
        String text = "";
        String name = TextFieldName.getText();
        
        text += "Name: " + name;
        text+= "\nSatisfication Level: ";
        
        if (RadioButton1.isSelected()) {
            text += "1";
        } 
        else if (RadioButton2.isSelected()) {
            text += "2";
        } 
        else if (RadioButton3.isSelected()) {
            text += "3";
        } 
        else if (RadioButton4.isSelected()) {
            text += "4";
        } 
        else {
            text += "5";
        }
        
        text += "\nYou Love The: ";
        if (CheckBoxDesign.isSelected()){
            text += "Design, ";
        }
        if (CheckBoxPerformance.isSelected()){
            text += "Performance, ";
        }
        if (CheckBoxUsability.isSelected()){
            text += "Usability ";
        }
        text += "\nYou Hear Us From: " + ComboBoxHear.getSelectedItem().toString();
//        JOptionPane.showMessageDialog(null, text);
        JOptionPane.showMessageDialog(null, text, "Result", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtonSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSend;
    private javax.swing.JCheckBox CheckBoxDesign;
    private javax.swing.JCheckBox CheckBoxPerformance;
    private javax.swing.JCheckBox CheckBoxUsability;
    private javax.swing.JComboBox<String> ComboBoxHear;
    private javax.swing.JLabel LabelFeatures;
    private javax.swing.JLabel LabelFeedback;
    private javax.swing.JLabel LabelHear;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelSatisfication;
    private javax.swing.JRadioButton RadioButton1;
    private javax.swing.JRadioButton RadioButton2;
    private javax.swing.JRadioButton RadioButton3;
    private javax.swing.JRadioButton RadioButton4;
    private javax.swing.JRadioButton RadioButton5;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.ButtonGroup buttonGroupSatisfication;
    // End of variables declaration//GEN-END:variables
}
