/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas2;

import java.awt.Color;

/**
 *
 * @author User
 */
public class SliderRGB extends javax.swing.JFrame {

    /**
     * Creates new form SliderRGB
     */
    public SliderRGB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRGB = new javax.swing.JLabel();
        SliderR = new javax.swing.JSlider();
        SliderG = new javax.swing.JSlider();
        SliderB = new javax.swing.JSlider();
        LabelRGB1 = new javax.swing.JLabel();
        LabelRGB2 = new javax.swing.JLabel();
        LabelRGB3 = new javax.swing.JLabel();
        LabelRGB4 = new javax.swing.JLabel();
        LabelRGB5 = new javax.swing.JLabel();
        LabelRGB6 = new javax.swing.JLabel();
        PanelColor = new javax.swing.JPanel();
        ButtonProgress = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelRGB.setFont(new java.awt.Font("Gotham Bold", 0, 24)); // NOI18N
        LabelRGB.setText("RGB Slider");

        SliderR.setMaximum(255);
        SliderR.setValue(255);
        SliderR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderRStateChanged(evt);
            }
        });

        SliderG.setMaximum(255);
        SliderG.setValue(255);
        SliderG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderGStateChanged(evt);
            }
        });

        SliderB.setMaximum(255);
        SliderB.setValue(255);
        SliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderBStateChanged(evt);
            }
        });

        LabelRGB1.setFont(new java.awt.Font("Gotham Bold", 0, 24)); // NOI18N
        LabelRGB1.setText("R");

        LabelRGB2.setFont(new java.awt.Font("Gotham Bold", 0, 24)); // NOI18N
        LabelRGB2.setText("G");

        LabelRGB3.setFont(new java.awt.Font("Gotham Bold", 0, 24)); // NOI18N
        LabelRGB3.setText("B");

        LabelRGB4.setFont(new java.awt.Font("Gotham Bold", 0, 24)); // NOI18N
        LabelRGB4.setText("255");

        LabelRGB5.setFont(new java.awt.Font("Gotham Bold", 0, 24)); // NOI18N
        LabelRGB5.setText("255");

        LabelRGB6.setFont(new java.awt.Font("Gotham Bold", 0, 24)); // NOI18N
        LabelRGB6.setText("255");

        javax.swing.GroupLayout PanelColorLayout = new javax.swing.GroupLayout(PanelColor);
        PanelColor.setLayout(PanelColorLayout);
        PanelColorLayout.setHorizontalGroup(
            PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelColorLayout.setVerticalGroup(
            PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        ButtonProgress.setText("Progress Bar");
        ButtonProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProgressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelRGB)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelRGB1)
                            .addComponent(LabelRGB2)
                            .addComponent(LabelRGB3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SliderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelRGB5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SliderR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelRGB4)
                                    .addComponent(LabelRGB6))))
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(ButtonProgress)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LabelRGB)
                .addGap(33, 33, 33)
                .addComponent(PanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SliderR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRGB1)
                    .addComponent(LabelRGB4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SliderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRGB2)
                    .addComponent(LabelRGB5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRGB3)
                    .addComponent(LabelRGB6))
                .addGap(18, 18, 18)
                .addComponent(ButtonProgress)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderRStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderRStateChanged
        // TODO add your handling code here:
        LabelRGB4.setText(Integer.toString(SliderR.getValue()));
        
        int r = SliderR.getValue();
        int g = SliderG.getValue();
        int b = SliderB.getValue();
        
        PanelColor.setBackground(new Color(r, g, b));
    }//GEN-LAST:event_SliderRStateChanged

    private void SliderGStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderGStateChanged
        // TODO add your handling code here:
        LabelRGB5.setText(Integer.toString(SliderR.getValue()));
        
        int r = SliderR.getValue();
        int g = SliderG.getValue();
        int b = SliderB.getValue();
        
        PanelColor.setBackground(new Color(r, g, b));
    }//GEN-LAST:event_SliderGStateChanged

    private void SliderBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderBStateChanged
        // TODO add your handling code here:
        LabelRGB6.setText(Integer.toString(SliderR.getValue()));
        
        int r = SliderR.getValue();
        int g = SliderG.getValue();
        int b = SliderB.getValue();
        
        PanelColor.setBackground(new Color(r, g, b));
    }//GEN-LAST:event_SliderBStateChanged

    private void ButtonProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProgressActionPerformed
        // TODO add your handling code here:
        // Buat window hitungluas
        new ProgressBar().setVisible(true);
        // Buat windows sekarang hilang
        this.setVisible(false);
    }//GEN-LAST:event_ButtonProgressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SliderRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SliderRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SliderRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SliderRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SliderRGB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonProgress;
    private javax.swing.JLabel LabelRGB;
    private javax.swing.JLabel LabelRGB1;
    private javax.swing.JLabel LabelRGB2;
    private javax.swing.JLabel LabelRGB3;
    private javax.swing.JLabel LabelRGB4;
    private javax.swing.JLabel LabelRGB5;
    private javax.swing.JLabel LabelRGB6;
    private javax.swing.JPanel PanelColor;
    private javax.swing.JSlider SliderB;
    private javax.swing.JSlider SliderG;
    private javax.swing.JSlider SliderR;
    // End of variables declaration//GEN-END:variables
}
