/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pertemuan4;

import java.awt.Color;

/**
 *
 * @author User
 */
public class FormSwing extends javax.swing.JFrame {

    /**
     * Creates new form FormSwing
     */
    public FormSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SliderR = new javax.swing.JSlider();
        LabelRed = new javax.swing.JLabel();
        LabelGreen = new javax.swing.JLabel();
        LabelBlue = new javax.swing.JLabel();
        SliderG = new javax.swing.JSlider();
        SliderB = new javax.swing.JSlider();
        LabelRed1 = new javax.swing.JLabel();
        LabelGreen1 = new javax.swing.JLabel();
        LabelBlue1 = new javax.swing.JLabel();
        PanelColor = new javax.swing.JPanel();
        Slider1 = new javax.swing.JSlider();
        Slider2 = new javax.swing.JSlider();
        ProgressBar1 = new javax.swing.JProgressBar();
        ButtonStart = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SliderR.setMaximum(255);
        SliderR.setValue(0);
        SliderR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderRStateChanged(evt);
            }
        });

        LabelRed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelRed.setText("R");

        LabelGreen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelGreen.setText("G");

        LabelBlue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelBlue.setText("B");

        SliderG.setMaximum(255);
        SliderG.setValue(0);
        SliderG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderGStateChanged(evt);
            }
        });

        SliderB.setMaximum(255);
        SliderB.setValue(0);
        SliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderBStateChanged(evt);
            }
        });

        LabelRed1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelRed1.setText("0");

        LabelGreen1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelGreen1.setText("0");

        LabelBlue1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelBlue1.setText("0");

        javax.swing.GroupLayout PanelColorLayout = new javax.swing.GroupLayout(PanelColor);
        PanelColor.setLayout(PanelColorLayout);
        PanelColorLayout.setHorizontalGroup(
            PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanelColorLayout.setVerticalGroup(
            PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Slider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider1StateChanged(evt);
            }
        });

        Slider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider2StateChanged(evt);
            }
        });

        ButtonStart.setText("Start");
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });

        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(ProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelGreen)
                                    .addComponent(LabelRed)
                                    .addComponent(LabelBlue))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SliderR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SliderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Slider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelRed1)
                            .addComponent(LabelGreen1)
                            .addComponent(LabelBlue1))
                        .addGap(61, 61, 61)
                        .addComponent(PanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LabelRed1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LabelGreen1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LabelBlue1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelRed)
                                .addComponent(SliderR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelGreen)
                                .addComponent(SliderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LabelBlue)
                                .addComponent(SliderB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(PanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Slider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Slider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonStart)
                        .addComponent(ButtonReset)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SliderRStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderRStateChanged
        // TODO add your handling code here:
        LabelRed1.setText(Integer.toString(SliderR.getValue()));
        
        int r = SliderR.getValue();
        int g = SliderG.getValue();
        int b = SliderB.getValue();
        
        PanelColor.setBackground(new Color(r, g, b));
    }//GEN-LAST:event_SliderRStateChanged

    private void SliderGStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderGStateChanged
        // TODO add your handling code here:
        LabelGreen1.setText(Integer.toString(SliderG.getValue()));
        
        int r = SliderR.getValue();
        int g = SliderG.getValue();
        int b = SliderB.getValue();
        
        PanelColor.setBackground(new Color(r, g, b));
    }//GEN-LAST:event_SliderGStateChanged

    private void SliderBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderBStateChanged
        // TODO add your handling code here:
        LabelBlue1.setText(Integer.toString(SliderB.getValue()));
        
        int r = SliderR.getValue();
        int g = SliderG.getValue();
        int b = SliderB.getValue();
        
        PanelColor.setBackground(new Color(r, g, b));
    }//GEN-LAST:event_SliderBStateChanged

    private void Slider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider1StateChanged
        // TODO add your handling code here:
        int slider1 = Slider1.getValue();
        
        Slider2.setValue(slider1);
    }//GEN-LAST:event_Slider1StateChanged

    private void Slider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider2StateChanged
        // TODO add your handling code here:
        int slider2 = Slider2.getValue();
        
        Slider1.setValue(slider2);
    }//GEN-LAST:event_Slider2StateChanged

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed
        // TODO add your handling code here:
        ProgressBar1.setValue(ProgressBar1.getValue() + 10);
    }//GEN-LAST:event_ButtonStartActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        // TODO add your handling code here:
        ProgressBar1.setValue(0);
    }//GEN-LAST:event_ButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonStart;
    private javax.swing.JLabel LabelBlue;
    private javax.swing.JLabel LabelBlue1;
    private javax.swing.JLabel LabelGreen;
    private javax.swing.JLabel LabelGreen1;
    private javax.swing.JLabel LabelRed;
    private javax.swing.JLabel LabelRed1;
    private javax.swing.JPanel PanelColor;
    private javax.swing.JProgressBar ProgressBar1;
    private javax.swing.JSlider Slider1;
    private javax.swing.JSlider Slider2;
    private javax.swing.JSlider SliderB;
    private javax.swing.JSlider SliderG;
    private javax.swing.JSlider SliderR;
    // End of variables declaration//GEN-END:variables
}
