/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pertemuan11;

import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;
import org.mariadb.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.io.UnsupportedEncodingException;

/**
 *
 * @author User
 */
public class crudDB extends javax.swing.JFrame {

    /**
     * Creates new form crudDB
     */
    public crudDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ButtonShowData = new javax.swing.JButton();
        TextFieldUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextFieldPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFieldNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RadioButtonLaki = new javax.swing.JRadioButton();
        RadioButtonPerempuan = new javax.swing.JRadioButton();
        ComboBoxAgama = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextFieldNoTelp = new javax.swing.JTextField();
        ButtonDelete = new javax.swing.JButton();
        ButtonUpdate = new javax.swing.JButton();
        TextFieldConfirmPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Nama", "Jenis Kelamin", "Agama", "No Telp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableData);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Database Akun");

        ButtonShowData.setText("Show Data");
        ButtonShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonShowDataActionPerformed(evt);
            }
        });

        TextFieldUsername.setColumns(10);

        jLabel2.setText("Username");

        TextFieldPassword.setColumns(10);

        jLabel3.setText("Password");

        jLabel4.setText("Nama");

        TextFieldNama.setColumns(10);

        jLabel7.setText("Jenis Kelamin");

        buttonGroup1.add(RadioButtonLaki);
        RadioButtonLaki.setText("Laki - Laki");
        RadioButtonLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonLakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonPerempuan);
        RadioButtonPerempuan.setText("Perempuan");
        RadioButtonPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonPerempuanActionPerformed(evt);
            }
        });

        ComboBoxAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen Protestan", "Kristen Katolik", "Hindu", "Buddha", "Konghucu" }));
        ComboBoxAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAgamaActionPerformed(evt);
            }
        });

        jLabel5.setText("Agama");

        jLabel6.setText("No Telp");

        TextFieldNoTelp.setColumns(10);

        ButtonDelete.setText("Delete Data");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonUpdate.setText("Update Data");
        ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdateActionPerformed(evt);
            }
        });

        TextFieldConfirmPassword.setColumns(10);

        jLabel8.setText("Confirm Password");

        ButtonAdd.setText("Add Data");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonShowData))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(RadioButtonLaki)
                            .addComponent(RadioButtonPerempuan)
                            .addComponent(ComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(TextFieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonLaki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioButtonPerempuan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonShowData)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonUpdate)
                    .addComponent(ButtonAdd))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel model;
    
    // SHOW DATA FUNCTION (READ)
    private void ButtonShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonShowDataActionPerformed
        model = (DefaultTableModel)TableData.getModel();
        
        String conn = "jdbc:mariadb://localhost:3306/pemvis25?user=root&password=";
        
        try {
            Connection connection = (Connection) DriverManager.getConnection(conn);
            Statement stmt;
            ResultSet rs;
            
            String SQL = "SELECT * FROM tb_akun";
            
            stmt = connection.createStatement();
            rs = stmt.executeQuery(SQL);
            
            model.setRowCount(0);
            
            while(rs.next()){
                String username = rs.getString("NameUser");
                String password = rs.getString("Pass");
                String namaLengkap = rs.getString("Name");
                String jenisKelamin = rs.getString("Kelamin");
                String agama = rs.getString("Agama");
                String nomorTelp = rs.getString("NomorTelp");
                
                // Display full gender text in table
                String jenisKelaminDisplay = jenisKelamin.equals("L") ? "Laki-Laki" : "Perempuan";
                
                model.addRow(new Object[] {username, password, namaLengkap, jenisKelaminDisplay, agama, nomorTelp});
            }
            
            rs.close();
            stmt.close();
            connection.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonShowDataActionPerformed

    // ADD DATA FUNCTION (CREATE)
    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        // Validate inputs
        if(TextFieldUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!");
            return;
        }
        
        if(TextFieldPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!");
            return;
        }
        
        if(!TextFieldPassword.getText().equals(TextFieldConfirmPassword.getText())) {
            JOptionPane.showMessageDialog(null, "Password dan Confirm Password tidak sama!");
            return;
        }
        
        if(TextFieldNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!");
            return;
        }
        
        if(!RadioButtonLaki.isSelected() && !RadioButtonPerempuan.isSelected()) {
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin!");
            return;
        }
        
        if(TextFieldNoTelp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telp tidak boleh kosong!");
            return;
        }
        
        String conn = "jdbc:mariadb://localhost:3306/pemvis25?user=root&password=";
        
        try {
            Connection connection = (Connection) DriverManager.getConnection(conn);
            
            // Get gender value
            String jenisKelamin = RadioButtonLaki.isSelected() ? "L" : "P";
            
            // Get agama value
            String agama = ComboBoxAgama.getSelectedItem().toString();
            
            // Hash password
            String hashedPassword = md5Java(TextFieldPassword.getText());
            
            // Use PreparedStatement to prevent SQL injection
            String SQL = "INSERT INTO tb_akun (NameUser, Pass, Name, Kelamin, Agama, NomorTelp) VALUES (?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pstmt = connection.prepareStatement(SQL);
            pstmt.setString(1, TextFieldUsername.getText());
            pstmt.setString(2, hashedPassword);
            pstmt.setString(3, TextFieldNama.getText());
            pstmt.setString(4, jenisKelamin);
            pstmt.setString(5, agama);
            pstmt.setString(6, TextFieldNoTelp.getText());
            
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
            
            // Clear fields
            clearFields();
            
            // Refresh table
            ButtonShowDataActionPerformed(evt);
            
            pstmt.close();
            connection.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error menambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonAddActionPerformed

    // UPDATE DATA FUNCTION
    private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdateActionPerformed
        // Validate inputs
        if(TextFieldUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong!");
            return;
        }
        
        if(TextFieldNama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!");
            return;
        }
        
        if(!RadioButtonLaki.isSelected() && !RadioButtonPerempuan.isSelected()) {
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin!");
            return;
        }
        
        if(TextFieldNoTelp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telp tidak boleh kosong!");
            return;
        }
        
        String conn = "jdbc:mariadb://localhost:3306/pemvis25?user=root&password=";
        
        try {
            Connection connection = (Connection) DriverManager.getConnection(conn);
            
            // Get gender value
            String jenisKelamin = RadioButtonLaki.isSelected() ? "L" : "P";
            
            // Get agama value
            String agama = ComboBoxAgama.getSelectedItem().toString();
            
            // Check if updating password
            if(TextFieldPassword.getText().isEmpty() && TextFieldConfirmPassword.getText().isEmpty()) {
                // Update without password change
                String SQL = "UPDATE tb_akun SET Name = ?, Kelamin = ?, Agama = ?, NomorTelp = ? WHERE NameUser = ?";
                java.sql.PreparedStatement pstmt = connection.prepareStatement(SQL);
                pstmt.setString(1, TextFieldNama.getText());
                pstmt.setString(2, jenisKelamin);
                pstmt.setString(3, agama);
                pstmt.setString(4, TextFieldNoTelp.getText());
                pstmt.setString(5, TextFieldUsername.getText());
                
                int rowsAffected = pstmt.executeUpdate();
                
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
                    clearFields();
                    ButtonShowDataActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Username tidak ditemukan!");
                }
                
                pstmt.close();
            }
            else if(TextFieldPassword.getText().equals(TextFieldConfirmPassword.getText())) {
                // Update with password change
                String hashedPassword = md5Java(TextFieldPassword.getText());
                
                String SQL = "UPDATE tb_akun SET Pass = ?, Name = ?, Kelamin = ?, Agama = ?, NomorTelp = ? WHERE NameUser = ?";
                java.sql.PreparedStatement pstmt = connection.prepareStatement(SQL);
                pstmt.setString(1, hashedPassword);
                pstmt.setString(2, TextFieldNama.getText());
                pstmt.setString(3, jenisKelamin);
                pstmt.setString(4, agama);
                pstmt.setString(5, TextFieldNoTelp.getText());
                pstmt.setString(6, TextFieldUsername.getText());
                
                int rowsAffected = pstmt.executeUpdate();
                
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
                    clearFields();
                    ButtonShowDataActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Username tidak ditemukan!");
                }
                
                pstmt.close();
            }
            else {
                JOptionPane.showMessageDialog(null, "Password dan Confirm Password tidak sama!");
            }
            
            connection.close();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error mengupdate data: " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonUpdateActionPerformed

    // DELETE DATA FUNCTION
    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // Validate input
        if(TextFieldUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan username yang akan dihapus!");
            return;
        }
        
        // Confirmation dialog
        int confirm = JOptionPane.showConfirmDialog(null, 
            "Apakah Anda yakin ingin menghapus akun ini?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION) {
            String conn = "jdbc:mariadb://localhost:3306/pemvis25?user=root&password=";
            
            try {
                Connection connection = (Connection) DriverManager.getConnection(conn);
                
                // Use PreparedStatement to prevent SQL injection
                String SQL = "DELETE FROM tb_akun WHERE NameUser = ?";
                java.sql.PreparedStatement pstmt = connection.prepareStatement(SQL);
                pstmt.setString(1, TextFieldUsername.getText());
                
                int rowsAffected = pstmt.executeUpdate();
                
                if(rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                    clearFields();
                    ButtonShowDataActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(null, "Username tidak ditemukan!");
                }
                
                pstmt.close();
                connection.close();
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Error menghapus data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    // TABLE MOUSE CLICK HANDLER (for selecting row to update/delete)
    private void TableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataMouseClicked
        int row = TableData.getSelectedRow();
        
        if(row == -1) {
            return;
        }
        
        try {
            // Populate Username (Column 0)
            String username = TableData.getValueAt(row, 0).toString();
            TextFieldUsername.setText(username);
            
            // Skip Password (Column 1) - Don't populate for security
            
            // Populate Nama (Column 2)
            String nama = TableData.getValueAt(row, 2).toString();
            TextFieldNama.setText(nama);
            
            // Populate Jenis Kelamin (Column 3)
            String jenisKelamin = TableData.getValueAt(row, 3).toString();
            if(jenisKelamin.equalsIgnoreCase("Laki-Laki") || jenisKelamin.equalsIgnoreCase("L")) {
                RadioButtonLaki.setSelected(true);
            } else if(jenisKelamin.equalsIgnoreCase("Perempuan") || jenisKelamin.equalsIgnoreCase("P")) {
                RadioButtonPerempuan.setSelected(true);
            }
            
            // Populate Agama (Column 4)
            String agama = TableData.getValueAt(row, 4).toString();
            ComboBoxAgama.setSelectedItem(agama);
            
            // Populate No Telp (Column 5)
            String nomorTelp = TableData.getValueAt(row, 5).toString();
            TextFieldNoTelp.setText(nomorTelp);
            
            // Clear password fields for security
            TextFieldPassword.setText("");
            TextFieldConfirmPassword.setText("");
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error memuat data: " + e.getMessage());
        }
    }//GEN-LAST:event_TableDataMouseClicked

    private void RadioButtonLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonLakiActionPerformed

    private void RadioButtonPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonPerempuanActionPerformed

    private void ComboBoxAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAgamaActionPerformed

    // MD5 HASHING FUNCTION
    private String md5Java(String message) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] digest = md.digest(message.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder();
            for (byte b : digest) {
                sb.append(String.format("%02x", b & 0xff));
            }
            return sb.toString();
        } catch(NoSuchAlgorithmException | UnsupportedEncodingException e) {
            JOptionPane.showMessageDialog(null, "Error hashing password: " + e.getMessage());
            return "";
        }
    }
    
    // HELPER FUNCTION TO CLEAR ALL FIELDS
    private void clearFields() {
        TextFieldUsername.setText("");
        TextFieldPassword.setText("");
        TextFieldConfirmPassword.setText("");
        TextFieldNama.setText("");
        TextFieldNoTelp.setText("");
        buttonGroup1.clearSelection();
        ComboBoxAgama.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonShowData;
    private javax.swing.JButton ButtonUpdate;
    private javax.swing.JComboBox<String> ComboBoxAgama;
    private javax.swing.JRadioButton RadioButtonLaki;
    private javax.swing.JRadioButton RadioButtonPerempuan;
    private javax.swing.JTable TableData;
    private javax.swing.JTextField TextFieldConfirmPassword;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldNoTelp;
    private javax.swing.JTextField TextFieldPassword;
    private javax.swing.JTextField TextFieldUsername;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
