
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class FormRegister extends javax.swing.JFrame {

    /**
     * Creates new form FormRegister
     */
    public FormRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKelamin = new javax.swing.ButtonGroup();
        LabelUser = new javax.swing.JLabel();
        FieldPassword = new javax.swing.JPasswordField();
        LabelPassword = new javax.swing.JLabel();
        FieldUser = new javax.swing.JTextField();
        ButtonRegister = new javax.swing.JButton();
        LabelForm = new javax.swing.JLabel();
        FieldConfirmPassword = new javax.swing.JPasswordField();
        LabelConfirmPassword = new javax.swing.JLabel();
        LabelJenisKelamin = new javax.swing.JLabel();
        RadioButtonLaki = new javax.swing.JRadioButton();
        RadioButtonPerempuan = new javax.swing.JRadioButton();
        ButtonLogin = new javax.swing.JButton();
        LabelSIM = new javax.swing.JLabel();
        CheckBoxSIMA = new javax.swing.JCheckBox();
        CheckBoxSIMC = new javax.swing.JCheckBox();
        CheckBoxSIMB = new javax.swing.JCheckBox();
        LabelAgama = new javax.swing.JLabel();
        ComboBoxAgama = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        LabelAlamat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelUser.setText("User");

        FieldPassword.setColumns(10);

        LabelPassword.setText("Password");

        FieldUser.setColumns(10);
        FieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUserActionPerformed(evt);
            }
        });

        ButtonRegister.setText("Register");
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });

        LabelForm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelForm.setText("Form Register");

        FieldConfirmPassword.setColumns(10);

        LabelConfirmPassword.setText("Confirm Password");

        LabelJenisKelamin.setText("Jenis Kelamin");

        buttonGroupKelamin.add(RadioButtonLaki);
        RadioButtonLaki.setSelected(true);
        RadioButtonLaki.setText("Laki Laki");

        buttonGroupKelamin.add(RadioButtonPerempuan);
        RadioButtonPerempuan.setText("Perempuan");

        ButtonLogin.setText("Login");
        ButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginActionPerformed(evt);
            }
        });

        LabelSIM.setText("SIM");

        CheckBoxSIMA.setText("SIM A");
        CheckBoxSIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSIMAActionPerformed(evt);
            }
        });

        CheckBoxSIMC.setText("SIM B");
        CheckBoxSIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSIMCActionPerformed(evt);
            }
        });

        CheckBoxSIMB.setText("SIM C");
        CheckBoxSIMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSIMBActionPerformed(evt);
            }
        });

        LabelAgama.setText("Agama");

        ComboBoxAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Protestan", "Katolik", "Hindu", "Buddha", "Konghucu" }));
        ComboBoxAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAgamaActionPerformed(evt);
            }
        });

        TextArea1.setColumns(20);
        TextArea1.setLineWrap(true);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        LabelAlamat.setText("Alamat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelForm)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelConfirmPassword)
                                    .addComponent(LabelJenisKelamin)
                                    .addComponent(LabelAgama)
                                    .addComponent(LabelAlamat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(RadioButtonLaki)
                                    .addComponent(FieldConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RadioButtonPerempuan)
                                    .addComponent(CheckBoxSIMA)
                                    .addComponent(CheckBoxSIMC)
                                    .addComponent(CheckBoxSIMB)
                                    .addComponent(ComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelSIM)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(ButtonRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LabelForm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUser)
                    .addComponent(FieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPassword)
                    .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelConfirmPassword)
                    .addComponent(FieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJenisKelamin)
                    .addComponent(RadioButtonLaki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonPerempuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSIM)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CheckBoxSIMA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxSIMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBoxSIMB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAgama)
                    .addComponent(ComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegister)
                    .addComponent(ButtonLogin))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUserActionPerformed

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        // TODO add your handling code here:
        String text = "";
        String name = FieldUser.getText();
        String password = FieldPassword.getText();
        String confirm_password = FieldConfirmPassword.getText();
        
        
        text += "Username: " + name;
        text += "\nPassword Valid: " + password.equals(confirm_password);
        text += "\nJenis Kelamin: ";
        if (RadioButtonLaki.isSelected()) {
            text += "Laki Laki";
        }
        else {
            text += "Perempuan";
        }
        text += "\nSIM: ";
        if (CheckBoxSIMA.isSelected()){
            text += "A ";
        }
        if (CheckBoxSIMB.isSelected()){
            text += "B ";
        }
        if (CheckBoxSIMC.isSelected()){
            text += "C ";
        }
        text += "\nAgama: " + ComboBoxAgama.getSelectedItem().toString();
        
        text += "\nAlamat: " + TextArea1.getText();
                
        JOptionPane.showMessageDialog(null, text);
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void ButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginActionPerformed
        // TODO add your handling code here:
        // Buat window hitungluas
        new FormLogin().setVisible(true);
        // Buat windows sekarang hilang
        this.setVisible(false);
    }//GEN-LAST:event_ButtonLoginActionPerformed

    private void CheckBoxSIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSIMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxSIMAActionPerformed

    private void CheckBoxSIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSIMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxSIMCActionPerformed

    private void CheckBoxSIMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxSIMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxSIMBActionPerformed

    private void ComboBoxAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAgamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JCheckBox CheckBoxSIMA;
    private javax.swing.JCheckBox CheckBoxSIMB;
    private javax.swing.JCheckBox CheckBoxSIMC;
    private javax.swing.JComboBox<String> ComboBoxAgama;
    private javax.swing.JPasswordField FieldConfirmPassword;
    private javax.swing.JPasswordField FieldPassword;
    private javax.swing.JTextField FieldUser;
    private javax.swing.JLabel LabelAgama;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelConfirmPassword;
    private javax.swing.JLabel LabelForm;
    private javax.swing.JLabel LabelJenisKelamin;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelSIM;
    private javax.swing.JLabel LabelUser;
    private javax.swing.JRadioButton RadioButtonLaki;
    private javax.swing.JRadioButton RadioButtonPerempuan;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.ButtonGroup buttonGroupKelamin;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
